language: cpp
 
 # Make sure to install ccache locally as well

# You may find that on your travis CI or on the master branch that for some reason travis is timing out,
# ccache can fix this if you compile the dependency manager one at a time since VTK takes 50 minutes to compile on travis
# To do this, go into the superbuild cmake and simply comment out the packages so that opencv only builds, then vtk and opencv, etc
# After that, also make sure the script terminates afterwards immediately so travis can pack and upload the cache
cache: 
  - ccache
  # - directories:
  #   - /Users/travis/build/PhucNgo1711/CaPTk/bin
  #   - /usr/local/Cellar/llvm
  #   - /usr/local/opt/llvm
  #   - /usr/local/Cellar/make
  #   - /usr/local/opt/make
  - timeout: 1000

env:
  global:
    - MAKEFLAGS="-j 2"

# Build matrix to run jobs in parallel
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env:
        - LINUX_DIST=xenial
    - os: linux
      dist: trusty
      sudo: required
      env:
        - LINUX_DIST=trusty
    - os: osx
  fast_finish: true
  allow_failures:
    - os: linux
      dist: trusty

before_install:
  ### LINUX
  # Linux install step
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$LINUX_DIST" == "xenial" ]]; then sudo apt-get install -qq gcc g++ make libgl-dev cmake python3-pip python-numpy; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$LINUX_DIST" == "trusty" ]]; then sudo apt-get install -qq gcc g++ make libgl1-mesa-dev cmake python3-pip python-numpy; fi
  
  # Update step
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

  # Git LFS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git lfs fetch --all; fi

  ### OSX
  # OSX install step
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache && export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install caskroom/cask/mactex ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install make llvm && export PATH="/usr/local/opt/make/libexec/gnubin:$PATH" ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -d /usr/local/opt/make/lib  || { rmdir /usr/local/opt/make; HOMEBREW_NO_AUTO_UPDATE=1 brew install make; }; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then test -d /usr/local/opt/llvm/lib  || { rmdir /usr/local/opt/llvm; HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm; }; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs install && git lfs fetch --all; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/linux-generic.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/mac-test-build.sh; fi
