language: cpp

# Make sure to install ccache locally as well
cache: ccache

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
  fast_finish: true
  # Temporary, used for testing
  allow_failures:
    - os: linux
      dist: trusty

before_install:
  # Linux install step
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gcc g++ make libgl-dev cmake python3-pip python-numpy; fi
  
  # Update step
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

  # Git LFS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git lfs fetch --all; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis/linux-generic.sh; fi