language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
  - os: osx
  fast_finish: true 
  allow_failures:
    - os: linux
    - os: osx

before_install:
  ### LINUX
  # Linux install step
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gcc g++ make libgl-dev cmake python3-pip python-numpy; fi
  
  # Update step
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

  # Git LFS
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git lfs fetch --all; fi

  ### OSX
  # OSX install step
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install caskroom/cask/mactex; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt make git-lfs doxygen llvm ; fi
  # caskroom/cask/mactex
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs install; fi

  # Git LFS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs fetch --all; fi

# install: travis_wait 60
  # - brew install ccache
  # - export PATH="/usr/local/opt/ccache/libexec:$PATH"

script:
  ### LINUX
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/test-build.sh; fi

  ### OSX
  - travis_wait 60 if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/mac-test-build.sh; fi
