language: cpp

os:
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=511
#  - osx
#  - windows

matrix:
  fast_finish: true
  # Temporary, used for testing
  allow_failures:
    - os: linux

before_install:
  # Linux install step
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gcc g++ make cmake python3-pip python-numpy; fi
  
  # Load qt env into repos
  - if [[ "$QT_BASE" = "511" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y; fi
  
  # Update step
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

  # Install qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh;
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/test-build.sh; fi
