language: cpp
 
 # Make sure to install ccache locally as well

# You may find that on your travis CI or on the master branch that for some reason travis is timing out,
# ccache can fix this if you compile the dependency manager one at a time since VTK takes 50 minutes to compile on travis
# To do this, go into the superbuild cmake and simply comment out the packages so that opencv only builds, then vtk and opencv, etc
# After that, also make sure the script terminates afterwards immediately so travis can pack and upload the cache
cache: 
  # - ccache
  - directories:
    - /Users/travis/build/PhucNgo1711/CaPTk/bin/
  - timeout: 1200

# env:
#   global:
#     - MAKEFLAGS="-j 2"

# Build matrix to run jobs in parallel
matrix:
  include:
    - os: osx
  fast_finish: true

before_install:
  ### OSX
  # OSX install step
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ccache && export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install caskroom/cask/mactex ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install make git-lfs doxygen llvm && export PATH="/usr/local/opt/make/libexec/gnubin:$PATH" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git lfs install && git lfs fetch --all; fi
  
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/mac-test-build.sh; fi
