language: cpp

os:
  - linux
#  - osx
#  - windows

matrix:
  fast_finish: true
  # Temporary, used for testing
  allow_failures:
    - os: linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes gcc g++ make cmake python3-pip python-numpy; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ./scripts/test-build.sh; fi
