language: cpp

os:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=511
#  - osx
#  - windows

matrix:
  fast_finish: true
  # Temporary, used for testing
  allow_failures:
    - os: linux

before_install:
  # Linux install step
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes -qq gcc g++ make cmake python3-pip python-numpy; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/test-build.sh; fi
