# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: |
      set -x
      if [ -n "$(System.PullRequest.SourceCommitId)" ]; then
        git checkout $(System.PullRequest.SourceCommitId)
      fi
  displayName: 'Checkout pull request HEAD'

- script: |
      sudo apt-get install -qq gcc g++ make libgl-dev cmake python3-pip python-numpy dos2unix
  displayName: 'Install dependencies from Aptitude'

- script: |
      ./.travis/linux-generic.sh
  displayName: 'Launch Travis CI script'
